/* eslint-disable max-len */
/* eslint-disable @typescript-eslint/no-explicit-any */
import type {Request, Response} from "express";
import {db} from "../lib/admin.js";
import {populateDocuments} from "./populate.js";
import {
  buildRelationWeightMap,
  calculateRelevanceScore,
  extractSearchableFieldsWithRelations,
} from "./relevance.js";
import type {FilterCriteria, FilterGroup} from "./types.js";
import {
  applyCombinedSort,
  applySpecialFilters,
  matchesFilterGroup,
  parseFilters,
  parsePopulateOptions,
  parseSortCriteria,
  parseSpecialFilter,
  parseSpecialSort,
} from "./utilsCore.js";

const DEFAULT_COLLECTION = "services";

function getParams(req: Request): Record<string, any> {
  if (req.method === "POST") {
    return (req.body && typeof req.body === "object" ? req.body : {}) as Record<
      string,
      any
    >;
  }
  return req.query as Record<string, any>;
}

/**
 * Liste / recherche générique Firestore : filtres, tri, populate, score.
 * GET (query) ou POST (JSON body).
 */
export async function runSearchData(req: Request, res: Response): Promise<void> {
  res.set("Access-Control-Allow-Origin", "*");

  if (req.method === "OPTIONS") {
    res.set("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    res.set("Access-Control-Allow-Headers", "Content-Type");
    res.status(204).send("");
    return;
  }

  if (req.method !== "GET" && req.method !== "POST") {
    res.status(405).setHeader("Allow", "GET, POST, OPTIONS").send("Method Not Allowed");
    return;
  }

  try {
    const params = getParams(req);

    const collectionName = (params.collection as string) || DEFAULT_COLLECTION;
    let searchQuery = (params.query as string) || (params.q as string);
    const limit = parseInt(String(params.limit), 10) || 50;
    const page = parseInt(String(params.page), 10) || 1;
    const minScore = parseFloat(String(params.minScore)) || 0;

    const returnAll = searchQuery === "*";
    if (returnAll) {
      searchQuery = "";
    }

    const filterGroup = parseFilters(params.filters);
    const sortCriteria = parseSortCriteria(params.sort || params.sortBy);
    const populateOptions = parsePopulateOptions(params.populate);
    const specialFilter = parseSpecialFilter(params.specialFilter);
    const specialSort = parseSpecialSort(params.specialSort);

    let customFields = params.fields;
    if (typeof customFields === "string") {
      customFields = customFields.split(",").map((f: string) => f.trim());
    }

    let fieldWeights: {[key: string]: number} = {};
    if (params.weights) {
      fieldWeights =
        typeof params.weights === "string" ?
          JSON.parse(params.weights) :
          params.weights;
    }

    if (page < 1) {
      res.status(400).json({
        success: false,
        error: "Page number must be greater than 0",
      });
      return;
    }

    const snapshot = await db.collection(collectionName).get();

    if (snapshot.empty) {
      res.status(200).json({
        success: true,
        message: "No documents found in collection",
        data: [],
        searchQuery: searchQuery || null,
        searchTerms: searchQuery ?
          searchQuery.toLowerCase().trim().split(/\s+/) :
          [],
        totalDocuments: 0,
        filters: filterGroup,
        sort: sortCriteria,
        returnAll,
        specialFilter,
        pagination: {
          page: 1,
          limit,
          totalPages: 0,
          totalResults: 0,
          hasNextPage: false,
          hasPrevPage: false,
        },
      });
      return;
    }

    const allDocuments: any[] = [];
    snapshot.forEach((doc) => {
      allDocuments.push({
        id: doc.id,
        ...doc.data(),
      });
    });

    if (
      searchQuery &&
      searchQuery.trim().length > 0 &&
      customFields &&
      customFields.length > 0
    ) {
      const autoGeneratedSearchFilters: FilterCriteria[] = (
        customFields as string[]
      ).map((field) => ({
        field,
        operator: "contains" as const,
        value: searchQuery,
      }));

      const searchFilterGroup: FilterGroup = {
        logic: "or",
        filters: autoGeneratedSearchFilters,
      };

      if (filterGroup.filters && filterGroup.filters.length > 0) {
        filterGroup.filters.push(searchFilterGroup);
      } else {
        filterGroup.filters = autoGeneratedSearchFilters;
        filterGroup.logic = "or";
      }
    }

    const hasReversePopulation = populateOptions.some(
      (p) => p.link && !p.field,
    );
    const hasFilters = filterGroup.filters && filterGroup.filters.length > 0;

    let documentsBeforeFilter = allDocuments;
    let alreadyPopulatedForFilter = false;

    if (hasReversePopulation && hasFilters) {
      documentsBeforeFilter = await populateDocuments(
        allDocuments,
        populateOptions,
      );
      alreadyPopulatedForFilter = true;
    }

    let filteredDocuments = documentsBeforeFilter;
    if (hasFilters) {
      filteredDocuments = documentsBeforeFilter.filter((doc) =>
        matchesFilterGroup(doc, filterGroup),
      );
    }

    if (specialFilter) {
      filteredDocuments = applySpecialFilters(
        filteredDocuments,
        specialFilter,
        collectionName,
      );
    }

    if (!searchQuery || searchQuery.trim().length === 0 || returnAll) {
      let populatedResults = filteredDocuments;

      if (!alreadyPopulatedForFilter) {
        populatedResults = await populateDocuments(
          filteredDocuments,
          populateOptions,
        );
      }

      const sortedDocuments = applyCombinedSort(
        populatedResults,
        specialSort,
        sortCriteria,
        collectionName,
      );

      const totalResults = sortedDocuments.length;
      const totalPages = Math.ceil(totalResults / limit);
      const startIndex = (page - 1) * limit;
      const endIndex = startIndex + limit;

      if (page > totalPages && totalResults > 0) {
        res.status(400).json({
          success: false,
          error: `Page ${page} does not exist. Total pages: ${totalPages}`,
        });
        return;
      }

      const paginatedResults = sortedDocuments.slice(startIndex, endIndex);

      const includeDistance =
        params.includeDistance === "true" || params.includeDistance === true;
      const resultsToReturn = paginatedResults.map((doc) => {
        const {distanceRaw: _omitRaw, ...docWithoutRaw} = doc;

        if (!includeDistance && specialSort?.type === "distance") {
          const {distance: _omitDist, ...rest} = docWithoutRaw;
          return rest;
        }

        return docWithoutRaw;
      });

      const pagination = {
        page,
        limit,
        totalPages,
        totalResults,
        hasNextPage: page < totalPages,
        hasPrevPage: page > 1,
        nextPage: page < totalPages ? page + 1 : null,
        prevPage: page > 1 ? page - 1 : null,
        startIndex: startIndex + 1,
        endIndex: Math.min(endIndex, totalResults),
      };

      res.status(200).json({
        success: true,
        count: resultsToReturn.length,
        totalDocuments: allDocuments.length,
        filteredDocuments: filteredDocuments.length,
        filters: filterGroup,
        sort: sortCriteria,
        populate: populateOptions,
        returnAll,
        specialFilter,
        specialSort,
        pagination,
        data: resultsToReturn,
      });
      return;
    }

    let populatedDocuments = filteredDocuments;
    if (!alreadyPopulatedForFilter) {
      populatedDocuments = await populateDocuments(
        filteredDocuments,
        populateOptions,
      );
    }

    const searchTerms = searchQuery
      .toLowerCase()
      .trim()
      .split(/\s+/)
      .filter((term) => term.length > 0);

    const relationFields = extractSearchableFieldsWithRelations(
      populatedDocuments,
      populateOptions,
      customFields as string[] | undefined,
    );

    const combinedWeights = buildRelationWeightMap(
      populateOptions,
      fieldWeights,
    );

    const scoredDocuments = populatedDocuments.map((doc) => {
      const score = calculateRelevanceScore(
        doc,
        searchTerms,
        relationFields,
        combinedWeights,
      );

      return {
        ...doc,
        _relevanceScore: score,
      };
    });

    let filteredAndSorted = scoredDocuments.filter(
      (doc) => doc._relevanceScore > minScore,
    );

    filteredAndSorted = applyCombinedSort(
      filteredAndSorted,
      specialSort,
      sortCriteria,
      collectionName,
    );

    if (!specialSort && (!sortCriteria || sortCriteria.length === 0)) {
      filteredAndSorted = filteredAndSorted.sort(
        (a, b) => b._relevanceScore - a._relevanceScore,
      );
    }

    const totalResults = filteredAndSorted.length;
    const totalPages = Math.ceil(totalResults / limit);
    const startIndex = (page - 1) * limit;
    const endIndex = startIndex + limit;

    if (page > totalPages && totalResults > 0) {
      res.status(400).json({
        success: false,
        error: `Page ${page} does not exist. Total pages: ${totalPages}`,
      });
      return;
    }

    const paginatedResults = filteredAndSorted.slice(startIndex, endIndex);

    const includeScore =
      params.includeScore === "true" || params.includeScore === true;
    const includeDistance =
      params.includeDistance === "true" || params.includeDistance === true;
    let results = paginatedResults;

    if (!includeScore) {
      results = results.map((doc) => {
        const {_relevanceScore: _omitScore, ...docWithoutScore} = doc;
        return docWithoutScore;
      });
    }

    if (!includeDistance && specialSort?.type === "distance") {
      results = results.map((doc) => {
        const {distance: _omitDist2, ...docWithoutDistance} = doc;
        return docWithoutDistance;
      });
    }

    const pagination = {
      page,
      limit,
      totalPages,
      totalResults,
      hasNextPage: page < totalPages,
      hasPrevPage: page > 1,
      nextPage: page < totalPages ? page + 1 : null,
      prevPage: page > 1 ? page - 1 : null,
      startIndex: startIndex + 1,
      endIndex: Math.min(endIndex, totalResults),
    };

    res.status(200).json({
      success: true,
      count: results.length,
      totalDocuments: allDocuments.length,
      filteredDocuments: filteredDocuments.length,
      searchQuery,
      searchTerms,
      searchableFields: relationFields.map((rf) => rf.path),
      filters: filterGroup,
      sort: sortCriteria,
      populate: populateOptions,
      specialFilter,
      pagination,
      data: results,
    });
  } catch (error: any) {
    console.error("Error searching documents:", error);
    res.status(500).json({
      success: false,
      error: error?.message || String(error),
    });
  }
}
